/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { Check, Save, Sparkles } from 'lucide-react'
import './ai-review.css'
import { request } from './api.js'

const categories = ['Pothole', 'Garbage / Waste', 'Broken Streetlight', 'Water Leakage', 'Road Damage', 'Drainage Issue', 'Fallen Tree', 'Traffic Signal Damage', 'Illegal Dumping', 'Public Infrastructure Damage', 'Other']
const severities = ['Low', 'Medium', 'High', 'Critical']

export default function AiReviewPanel({ issueId }) {
  const [issue, setIssue] = useState(null)
  const [departments, setDepartments] = useState([])
  const [form, setForm] = useState({ category: '', severity: '', priorityScore: 0, department: '', duplicateDecision: 'pending' })
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const load = async () => { const [issueResponse, departmentResponse] = await Promise.all([request({ url: `/issues/${issueId}` }), request({ url: '/departments' })]); const current = issueResponse.data.issue; setIssue(current); setDepartments(departmentResponse.data); setForm({ category: current.category, severity: current.severity, priorityScore: current.priorityScore, department: current.department?._id || '', duplicateDecision: current.ai?.duplicate?.isPotentialDuplicate ? 'pending' : 'rejected' }) }
  useEffect(() => { load().catch(() => setNotice('AI review data is unavailable.')) }, [issueId])
  const save = async (event) => { event.preventDefault(); setBusy(true); try { await request({ url: `/issues/${issueId}/ai-review`, method: 'put', data: { ...form, priorityScore: Number(form.priorityScore), department: form.department || null } }); setNotice('Admin review saved.'); await load() } catch (error) { setNotice(error.response?.data?.message || 'Unable to save the review.') } finally { setBusy(false) } }
  if (!issue) return <section className="ai-review-panel"><p>Loading AI review…</p></section>
  const ai = issue.ai || {}
  return <section className="ai-review-panel"><div className="ai-review-heading"><div><div className="eyebrow">Human oversight</div><h2><Sparkles size={18} /> AI recommendation review</h2></div><span className={`ai-pill ${ai.status || 'legacy'}`}>{ai.status || 'legacy'}</span></div><div className="ai-review-summary"><div><span>Model</span><b>{ai.modelName || 'Legacy baseline'}</b><small>{ai.modelVersion || 'No version recorded'}</small></div><div><span>Predicted category</span><b>{ai.category?.value || issue.category}</b><small>{ai.category?.confidence == null ? 'Confidence not available' : `${Math.round(ai.category.confidence * 100)}% confidence`}</small></div><div><span>Severity</span><b>{ai.severity?.value || issue.severity}</b><small>{ai.severity?.source || 'Existing recommendation'}</small></div><div><span>Priority</span><b>{ai.priorityScore ?? issue.priorityScore}/100</b><small>Recommendation</small></div><div><span>Duplicate</span><b>{ai.duplicate?.isPotentialDuplicate ? 'Possible match' : 'No match'}</b><small>{ai.duplicate?.similarityScore ? `${Math.round(ai.duplicate.similarityScore * 100)}% similarity` : 'Requires review'}</small></div></div><p className="ai-review-explanation">{ai.explanation || issue.aiResult?.explanation || 'No explanation is available.'}</p><form className="ai-review-form" onSubmit={save}><label>Effective category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Effective severity<select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value })}>{severities.map((severity) => <option key={severity}>{severity}</option>)}</select></label><label>Priority score<input type="number" min="0" max="100" value={form.priorityScore} onChange={(event) => setForm({ ...form, priorityScore: event.target.value })} /></label><label>Department<select value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })}><option value="">Unassigned</option>{departments.map((department) => <option value={department._id} key={department._id}>{department.name}</option>)}</select></label><label>Duplicate decision<select value={form.duplicateDecision} onChange={(event) => setForm({ ...form, duplicateDecision: event.target.value })}><option value="pending">Keep pending</option><option value="confirmed">Confirm duplicate</option><option value="rejected">Reject duplicate</option></select></label><button className="primary ai-save" disabled={busy}><Save size={16} /> {busy ? 'Saving…' : 'Save review'}</button></form>{notice && <p className="notice-inline">{notice}</p>}<p className="ai-review-note"><Check size={15} /> AI recommendations assist staff; explicit admin decisions remain authoritative.</p></section>
}
