import { useEffect, useMemo, useState } from 'react'
import './App.css'

const categories = ['Pothole', 'Garbage / Waste', 'Broken Streetlight', 'Water Leakage', 'Road Damage', 'Other']
const statuses = ['Reported', 'Under Review', 'In Progress', 'Resolved']
const departments = ['Roads & Transport', 'Sanitation', 'Electrical', 'Water Supply', 'Public Works']
const api = import.meta.env.VITE_API_URL || '/api'
const sampleIssues = [
  { _id: 'CC-1042', title: 'Large pothole near the bus stop', category: 'Pothole', location: 'MG Road, near Central Bus Stop', description: 'A deep pothole is causing vehicles to swerve into traffic.', severity: 'High', status: 'In Progress', department: 'Roads & Transport', createdAt: '2026-09-03T10:30:00Z' },
  { _id: 'CC-1041', title: 'Overflowing waste bin', category: 'Garbage / Waste', location: 'Green Park, Gate 2', description: 'The bin has not been cleared for several days.', severity: 'Medium', status: 'Under Review', department: 'Sanitation', createdAt: '2026-09-02T09:15:00Z' },
  { _id: 'CC-1039', title: 'Streetlight not working', category: 'Broken Streetlight', location: 'Lake View Avenue', description: 'The street is completely dark after sunset.', severity: 'Low', status: 'Reported', department: 'Electrical', createdAt: '2026-09-01T18:45:00Z' },
]
const date = (value) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value))
const Status = ({ status }) => <span className={`status ${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span>
const ref = (issue) => issue.reference || issue._id

export default function App() {
  const [view, setView] = useState('home'); const [issues, setIssues] = useState(sampleIssues); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true)
  const [filters, setFilters] = useState({ category: '', status: '', severity: '', query: '' })
  const load = async () => { try { const response = await fetch(`${api}/issues`); if (!response.ok) throw new Error(); setIssues(await response.json()); setNotice('') } catch { setNotice('Demo data is shown until the API is running.') } finally { setLoading(false) } }
  // Loading server data after first paint keeps the offline demo immediately usable.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load() }, [])
  const displayed = useMemo(() => issues.filter((issue) => (!filters.category || issue.category === filters.category) && (!filters.status || issue.status === filters.status) && (!filters.severity || issue.severity === filters.severity) && (!filters.query || `${issue.title} ${issue.location}`.toLowerCase().includes(filters.query.toLowerCase()))), [issues, filters])
  const submit = async (form) => { const local = { ...form, _id: `CC-${Math.floor(1000 + Math.random() * 9000)}`, status: 'Reported', department: 'Unassigned', createdAt: new Date().toISOString() }; try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => value && body.append(key, value)); const response = await fetch(`${api}/issues`, { method: 'POST', body }); if (!response.ok) throw new Error(); const saved = await response.json(); local._id = saved._id; local.reference = saved.reference; await load() } catch { setIssues((old) => [local, ...old]) } setView('my'); setNotice(`Your report ${ref(local)} has been submitted. You can track its progress below.`) }
  const update = async (id, change) => { setIssues((old) => old.map((issue) => issue._id === id ? { ...issue, ...change } : issue)); try { await fetch(`${api}/issues/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(change) }) } catch { setNotice('Change saved locally. Start the API to persist it.') } }
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView('home')}><span>✦</span> CivicConnect</button><nav><button className={view === 'home' ? 'active' : ''} onClick={() => setView('home')}>Home</button><button className={view === 'my' ? 'active' : ''} onClick={() => setView('my')}>My Issues</button><button className={view === 'admin' ? 'active' : ''} onClick={() => setView('admin')}>Authority Portal</button></nav><button className="profile-button" onClick={() => setView('report')}>＋ Report issue</button></header>{notice && <div className="notice">ℹ {notice}<button onClick={() => setNotice('')}>×</button></div>}{view === 'home' && <Home issues={issues} report={() => setView('report')} mine={() => setView('my')} />}{view === 'report' && <Report cancel={() => setView('home')} submit={submit} />}{view === 'my' && <MyIssues issues={issues} loading={loading} report={() => setView('report')} />}{view === 'admin' && <Admin issues={displayed} all={issues} filters={filters} setFilters={setFilters} update={update} />}<footer>© 2026 CivicConnect · Building better neighbourhoods, together.</footer></div>
}
function Home({ issues, report, mine }) { return <main><section className="hero-section"><div className="eyebrow">Civic action, made simple</div><h1>See a problem?<br /><em>Start a solution.</em></h1><p>Report local issues in minutes, follow their progress, and help create a city that works for everyone.</p><div className="hero-actions"><button className="primary" onClick={report}>Report an issue <span>→</span></button><button className="secondary" onClick={mine}>Track my reports</button></div></section><section className="stats"><div><strong>{issues.length}</strong><span>Issues reported</span></div><div><strong>{issues.filter((i) => i.status === 'Resolved').length}</strong><span>Issues resolved</span></div><div><strong>24h</strong><span>Average response</span></div></section><section className="how-section"><div><div className="eyebrow">How it works</div><h2>A clearer path from<br />complaint to change.</h2></div><div className="steps"><article><b>01</b><h3>Report it</h3><p>Tell us what happened, where it is, and add a photo if you can.</p></article><article><b>02</b><h3>We route it</h3><p>Your report reaches the team best placed to take action.</p></article><article><b>03</b><h3>Track progress</h3><p>Stay updated from review through to resolution.</p></article></div></section></main> }
function Report({ cancel, submit }) { const [form, setForm] = useState({ title: '', category: '', description: '', location: '', severity: 'Medium', image: null }); const [sending, setSending] = useState(false); const change = (e) => setForm({ ...form, [e.target.name]: e.target.type === 'file' ? e.target.files[0] : e.target.value }); const send = async (e) => { e.preventDefault(); setSending(true); await submit(form); setSending(false) }; return <main className="form-page"><button className="back" onClick={cancel}>← Back to home</button><div className="page-intro"><div className="eyebrow">New civic report</div><h1>Let’s get it fixed.</h1><p>Clear details help the right team respond faster.</p></div><form className="report-card" onSubmit={send}><div className="form-grid"><label className="full">Issue title<input required name="title" value={form.title} onChange={change} placeholder="e.g. Large pothole near the bus stop" /></label><label>Category<select required name="category" value={form.category} onChange={change}><option value="">Choose a category</option>{categories.map((x) => <option key={x}>{x}</option>)}</select></label><label>Severity<select name="severity" value={form.severity} onChange={change}>{['Low', 'Medium', 'High', 'Critical'].map((x) => <option key={x}>{x}</option>)}</select></label><label className="full">Location<input required name="location" value={form.location} onChange={change} placeholder="Street, landmark, ward or neighbourhood" /></label><label className="full">Description<textarea required name="description" value={form.description} onChange={change} rows="5" placeholder="What is the issue? Add details that will help the team locate and resolve it." /></label><label className="full upload">Add a photo<span>Optional · JPG, PNG or WEBP up to 5 MB</span><input name="image" type="file" accept="image/png,image/jpeg,image/webp" onChange={change} /></label></div><div className="form-bottom"><p>By submitting, you confirm that the information is accurate to the best of your knowledge.</p><button className="primary" disabled={sending}>{sending ? 'Submitting…' : 'Submit report →'}</button></div></form></main> }
function MyIssues({ issues, loading, report }) { return <main className="content-page"><div className="content-heading"><div><div className="eyebrow">Citizen dashboard</div><h1>My reported issues</h1><p>Follow every report from submission to resolution.</p></div><button className="primary" onClick={report}>＋ Report an issue</button></div>{loading ? <p className="empty">Loading your reports…</p> : <div className="issue-list">{issues.map((i) => <article className="issue-card" key={i._id}><div className="issue-icon">●</div><div className="issue-main"><div className="issue-topline"><span className="issue-id">{ref(i)}</span><Status status={i.status} /></div><h3>{i.title}</h3><p className="location">⌖ {i.location}</p><p className="issue-date">Reported {date(i.createdAt)} · {i.category}</p></div><div className="issue-progress"><div className="progress-label"><span>Progress</span><b>{statuses.indexOf(i.status) + 1}/4</b></div><div className="progress-track"><i style={{ width: `${((statuses.indexOf(i.status) + 1) / 4) * 100}%` }} /></div><small>{i.status === 'Resolved' ? 'This issue has been resolved.' : `Currently ${i.status.toLowerCase()}.`}</small></div></article>)}</div>}</main> }
function Admin({ issues, all, filters, setFilters, update }) { const filter = (key) => (e) => setFilters({ ...filters, [key]: e.target.value }); return <main className="content-page admin"><div className="content-heading"><div><div className="eyebrow">Authority portal</div><h1>Issue operations</h1><p>Prioritise, assign, and keep residents informed.</p></div></div><section className="admin-stats"><div><span>All reports</span><strong>{all.length}</strong></div><div><span>Awaiting resolution</span><strong>{all.filter((i) => i.status !== 'Resolved').length}</strong></div><div><span>High priority</span><strong>{all.filter((i) => ['High', 'Critical'].includes(i.severity)).length}</strong></div></section><section className="filterbar"><input value={filters.query} onChange={filter('query')} placeholder="Search issues or locations" /><select value={filters.category} onChange={filter('category')}><option value="">All categories</option>{categories.map((x) => <option key={x}>{x}</option>)}</select><select value={filters.severity} onChange={filter('severity')}><option value="">All severity levels</option>{['Low', 'Medium', 'High', 'Critical'].map((x) => <option key={x}>{x}</option>)}</select><select value={filters.status} onChange={filter('status')}><option value="">All statuses</option>{statuses.map((x) => <option key={x}>{x}</option>)}</select></section><section className="admin-table"><div className="table-head"><span>Issue</span><span>Priority</span><span>Assignment</span><span>Status</span></div>{issues.map((i) => <div className="table-row" key={i._id}><div><b>{i.title}</b><small>{ref(i)} · {i.category} · ⌖ {i.location}</small></div><span className={`severity ${i.severity.toLowerCase()}`}>{i.severity}</span><select value={i.department || 'Unassigned'} onChange={(e) => update(i._id, { department: e.target.value })}><option>Unassigned</option>{departments.map((x) => <option key={x}>{x}</option>)}</select><select value={i.status} onChange={(e) => update(i._id, { status: e.target.value })}>{statuses.map((x) => <option key={x}>{x}</option>)}</select></div>)}{!issues.length && <p className="empty">No issues match these filters.</p>}</section></main> }
