import { z } from 'zod'
import Issue from '../models/Issue.js'
import Department from '../models/Department.js'
import StatusHistory from '../models/StatusHistory.js'
import Comment from '../models/Comment.js'
import Notification from '../models/Notification.js'
import User from '../models/User.js'
import { CATEGORIES, SEVERITIES, STATUSES } from '../config/constants.js'
import { analyzeIssue } from '../services/ai.js'

const createSchema = z.object({ title: z.string().trim().min(5).max(120), description: z.string().trim().min(10).max(3000), category: z.enum(CATEGORIES), address: z.string().trim().min(3).max(300), latitude: z.coerce.number().min(-90).max(90).optional(), longitude: z.coerce.number().min(-180).max(180).optional(), ward: z.string().trim().max(100).optional(), landmark: z.string().trim().max(200).optional() })
const canAccess = (issue, auth) => auth.role === 'admin' || String(issue.citizen?._id || issue.citizen) === auth.userId || (auth.role === 'worker' && String(issue.assignedWorker?._id || issue.assignedWorker) === auth.userId) || (auth.role === 'department' && auth.department && String(issue.department?._id || issue.department) === String(auth.department))
const detailPopulate = (query) => query.populate('citizen', 'name email').populate('department', 'name code').populate('assignedWorker', 'name email')

export async function listIssues(req, res) { const { status, category, severity, department, search, page = 1, limit = 20, mine } = req.query; const filter = {}; if (status) filter.status = status; if (category) filter.category = category; if (severity) filter.severity = severity; if (department) filter.department = department; if (search) filter.$text = { $search: search }; if (mine === 'true' || req.auth.role === 'citizen') filter.citizen = req.auth.userId; if (req.auth.role === 'worker') filter.assignedWorker = req.auth.userId; if (req.auth.role === 'department') filter.department = req.auth.department || null; const take = Math.min(Number(limit) || 20, 100); const skip = (Math.max(Number(page) || 1, 1) - 1) * take; const [items, total] = await Promise.all([detailPopulate(Issue.find(filter).sort({ priorityScore: -1, createdAt: -1 }).skip(skip).limit(take)), Issue.countDocuments(filter)]); res.json({ items, page: Number(page), limit: take, total, pages: Math.ceil(total / take) }) }
export async function createIssue(req, res) { const input = createSchema.parse(req.body); const coordinates = input.longitude !== undefined && input.latitude !== undefined ? [input.longitude, input.latitude] : undefined; const analysis = await analyzeIssue({ ...input, coordinates }); const department = await Department.findOne({ name: analysis.departmentName }); const issue = await Issue.create({ citizen: req.auth.userId, title: input.title, description: input.description, category: input.category, severity: analysis.severity, priorityScore: analysis.priorityScore, priorityLabel: analysis.priorityLabel, location: { address: input.address, ward: input.ward, landmark: input.landmark, coordinates }, images: req.files?.map((file) => ({ url: `/uploads/${file.filename}` })) || [], department: department?._id, possibleDuplicates: analysis.possibleDuplicates, aiResult: { category: analysis.category, categoryConfidence: analysis.categoryConfidence, severity: analysis.severity, severityScore: analysis.severityScore, explanation: analysis.explanation, analyzedAt: new Date() } }); await StatusHistory.create({ issue: issue._id, status: 'Reported', note: 'Issue submitted.', changedBy: req.auth.userId }); await Notification.create({ recipient: req.auth.userId, issue: issue._id, title: 'Report received', message: `Your report ${issue.reference} has been received.` }); res.status(201).json(await detailPopulate(Issue.findById(issue._id))) }
export async function getIssue(req, res) { const issue = await detailPopulate(Issue.findById(req.params.id)); if (!issue) return res.status(404).json({ message: 'Issue not found.' }); if (!canAccess(issue, req.auth)) return res.status(403).json({ message: 'You cannot view this issue.' }); const [history, comments] = await Promise.all([StatusHistory.find({ issue: issue._id }).sort({ createdAt: 1 }).populate('changedBy', 'name role'), Comment.find({ issue: issue._id, ...(req.auth.role === 'citizen' ? { visibility: 'public' } : {}) }).sort({ createdAt: 1 }).populate('author', 'name role')]); res.json({ issue, history, comments }) }
export async function updateStatus(req, res) { const { status, note } = z.object({ status: z.enum(STATUSES), note: z.string().trim().max(1000).optional() }).parse(req.body); const issue = await Issue.findById(req.params.id); if (!issue) return res.status(404).json({ message: 'Issue not found.' }); if (!canAccess(issue, req.auth) || req.auth.role === 'citizen') return res.status(403).json({ message: 'You cannot update this issue.' }); const previousStatus = issue.status; issue.status = status; if (status === 'Resolved') issue.resolvedAt = new Date(); await issue.save(); await StatusHistory.create({ issue: issue._id, status, previousStatus, note, changedBy: req.auth.userId }); await Notification.create({ recipient: issue.citizen, issue: issue._id, title: 'Issue status updated', message: `${issue.reference} is now ${status}.` }); res.json(issue) }
export async function assignIssue(req, res) { const { department, worker } = z.object({ department: z.string().optional(), worker: z.string().optional() }).parse(req.body); const issue = await Issue.findById(req.params.id); if (!issue) return res.status(404).json({ message: 'Issue not found.' }); if (req.auth.role === 'department' && String(issue.department) !== String(req.auth.department)) return res.status(403).json({ message: 'You can only assign issues in your department.' }); if (department) { const target = await Department.findById(department); if (!target) return res.status(422).json({ message: 'Choose a valid department.' }); issue.department = target._id } if (worker) { const user = await User.findById(worker); if (!user || !['worker', 'department'].includes(user.role)) return res.status(422).json({ message: 'Choose a valid worker.' }); if (issue.department && String(user.department) !== String(issue.department)) return res.status(422).json({ message: 'The worker must belong to the assigned department.' }); issue.assignedWorker = user._id; await Notification.create({ recipient: user._id, issue: issue._id, type: 'assignment', title: 'New issue assignment', message: `${issue.reference} has been assigned to you.` }) } issue.status = issue.status === 'Reported' ? 'Assigned' : issue.status; await issue.save(); await StatusHistory.create({ issue: issue._id, status: issue.status, note: 'Assignment updated.', changedBy: req.auth.userId }); res.json(await detailPopulate(Issue.findById(issue._id))) }
export async function addComment(req, res) { const { body, visibility = 'public' } = z.object({ body: z.string().trim().min(1).max(2000), visibility: z.enum(['public', 'internal']).optional() }).parse(req.body); const issue = await Issue.findById(req.params.id); if (!issue || !canAccess(issue, req.auth)) return res.status(404).json({ message: 'Issue not found.' }); if (visibility === 'internal' && req.auth.role === 'citizen') return res.status(403).json({ message: 'Citizens cannot add internal notes.' }); const comment = await Comment.create({ issue: issue._id, author: req.auth.userId, body, visibility }); if (req.auth.role !== 'citizen' && visibility === 'public') await Notification.create({ recipient: issue.citizen, issue: issue._id, type: 'comment', title: 'New update on your report', message: body.slice(0, 180) }); res.status(201).json(await comment.populate('author', 'name role')) }
export async function confirmResolution(req, res) { const issue = await Issue.findById(req.params.id); if (!issue || String(issue.citizen) !== req.auth.userId) return res.status(404).json({ message: 'Issue not found.' }); issue.citizenConfirmedAt = new Date(); if (issue.status === 'Resolved') issue.status = 'Closed'; await issue.save(); await StatusHistory.create({ issue: issue._id, status: issue.status, previousStatus: 'Resolved', note: 'Resolution confirmed by citizen.', changedBy: req.auth.userId }); res.json(issue) }
